import { NavLink } from 'react-router-dom'
import { Archive, Bell, BriefcaseBusiness, ChartNoAxesCombined, CircleHelp, Command, Gauge, LayoutDashboard, LogOut, ShieldCheck, SlidersHorizontal, Ticket, UsersRound, X } from 'lucide-react'
import { useWorkspace } from '../../contexts/WorkspaceContext'

const sections = [
  { title: 'Workspace', items: [{ path: '/dashboard', title: 'Dashboard', icon: LayoutDashboard }, { path: '/tickets', title: 'Daftar tiket', icon: Ticket, key: 'tickets' }] },
  { title: 'Operasional', items: [{ path: '/assignments', title: 'Penugasan', icon: UsersRound }, { path: '/reports', title: 'Laporan', icon: ChartNoAxesCombined }] },
  { title: 'Konfigurasi', items: [{ path: '/admin/spk', title: 'Konfigurasi SPK', icon: SlidersHorizontal }, { path: '/admin/sla', title: 'Kebijakan SLA', icon: Gauge }, { path: '/admin/users', title: 'Pengguna & role', icon: UsersRound }, { path: '/admin/master-data', title: 'Data master', icon: BriefcaseBusiness }, { path: '/admin/audit', title: 'Audit trail', icon: ShieldCheck }] },
]
const roleAccess = { Pelapor: ['/dashboard', '/tickets'], Teknisi: ['/dashboard', '/tickets', '/assignments', '/reports'], Manajemen: ['/dashboard', '/reports'], Helpdesk: ['/dashboard', '/tickets', '/assignments', '/reports', '/admin/spk'], Supervisor: ['/dashboard', '/tickets', '/assignments', '/reports', '/admin/spk', '/admin/sla', '/admin/audit'], Administrator: sections.flatMap((section) => section.items.map((item) => item.path)) }

export function Sidebar({ open, onClose }) {
  const { user, logout } = useWorkspace()
  const allowed = roleAccess[user?.role] || roleAccess.Supervisor
  return <><aside className={`sidebar ${open ? 'sidebar-open' : ''}`}><div className="brand"><div className="brand-mark"><Command size={19} /></div><div><strong>prioritas</strong><span>Service Desk</span></div><button className="icon-button mobile-close" onClick={onClose} aria-label="Tutup navigasi"><X size={18} /></button></div><button className="workspace-select"><span className="workspace-avatar">N</span><span className="workspace-copy"><strong>Nusantara Digital</strong><small>IT Operations</small></span><Archive size={14} /></button><nav className="side-nav" aria-label="Navigasi utama">{sections.map((section) => { const items = section.items.filter((item) => allowed.includes(item.path)); return items.length > 0 && <div className="nav-group" key={section.title}><p className="nav-label">{section.title}</p>{items.map(({ path, title, icon: Icon, key }) => <NavLink key={path} to={path} className={({ isActive }) => `nav-link ${isActive ? 'active' : ''}`} onClick={onClose}><Icon size={17} strokeWidth={1.8} /><span>{title}</span>{key === 'tickets' && <span className="nav-count">18</span>}</NavLink>)}</div> })}</nav><div className="sidebar-bottom"><NavLink className="nav-link" to="/admin/audit" onClick={onClose}><Bell size={17} /><span>Aktivitas terbaru</span></NavLink><button className="nav-link" onClick={() => window.alert('Pusat bantuan tersedia saat layanan backend diaktifkan.')}><CircleHelp size={17} /><span>Pusat bantuan</span></button><div className="profile"><div className="profile-avatar">{user?.name?.split(' ').map((part) => part[0]).slice(0, 2).join('') || 'RA'}</div><div className="profile-copy"><strong>{user?.name || 'Raka Aditya'}</strong><span>{user?.role || 'Supervisor'}</span></div><button className="icon-button" onClick={logout} aria-label="Keluar"><LogOut size={16} /></button></div></div></aside>{open && <button className="nav-scrim" onClick={onClose} aria-label="Tutup navigasi" />}</>
}
